# Generated by Django 2.0 on 2018-11-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20181103_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='keyword',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
